export enum ROUTES {
  HOME = "/",
  NEWS = "/news/",
  OFFERS = "/offers/",
  SERVICE_CENTER = "/service-center/",
  IT_SERVICE = "/it-service/",
  SKUD = "/skud/",
  PRINT_3D = "/print-3d/",
  OWN_PRODUCTS = "/own-products/",
  PRICE_LIST = "/price-list/",
  DELIVERY = "/delivery/",
  GUARANTEE = "/guarantee/",
  GOV_PURCHASES = "/gov-purchases/",
  FZ_44_223 = "/fz-44-223/",
  DISPOSAL = "/disposal/",
  USEFUL_TIPS = "/useful-tips/",
  PARTNERSHIP = "/partnership/",
  CERTIFICATES = "/certificates/",
  INFO = "/info/",
}
